server:
    port: 8091

message.service.url: http://localhost:8090/message

spring.profiles.active: ca

logging.level.org.springframework.web: debug
logging.level.org.springframework.security: trace
logging.level.org.springframework.web-security: trace

---
# Keycloak configuration

spring:
  profiles: keycloak

logging.level.org.keycloak : trace

oauth:
  clientId: product-service
  clientSecret: 6d30a0b4-eec5-417c-b2d5-b18a1b11e8f1
  accessTokenUri: http://localhost:8180/auth/realms/SpringBoot/protocol/openid-connect/token

---

# CA API Gateway configuration

spring:
  profiles: ca

# The client Id & Secret can be found in the OAuth management app
oauth:
  clientId: 323ae95f-6bdc-4617-8613-bc86e255a3b1
  clientSecret: 9014b72f-f8d1-4e8b-9db9-877e56f5ab9f
  accessTokenUri: https://localhost:8443/auth/oauth/v2/token
  scope: read # separate scopes by ,
